import { defineStore } from 'pinia'

// ─── Vietnamese copy ──────────────────────────────────────────────────────────
const vi = {
  // Common nav
  nav: {
    home:       'Trang chủ',
    myTickets:  'Vé của tôi',
    scan:       'Soát vé',
    admin:      'Quản trị',
    settings:   'Cài đặt tài khoản',
    logout:     'Đăng xuất',
    back:       '← Quay lại',
  },

  // Auth
  auth: {
    login:              'Đăng nhập',
    register:           'Đăng ký',
    loginTitle:         'CHÀO MỪNG',
    loginSub:           'Đăng nhập bằng email hoặc số điện thoại',
    registerTitle:      'TẠO TÀI KHOẢN',
    registerSub:        'Đăng ký tài khoản hành khách mới',
    identifier:         'Email hoặc Số điện thoại',
    password:           'Mật khẩu',
    fullName:           'Họ và tên',
    phone:              'Số điện thoại',
    email:              'Email',
    confirmPassword:    'Xác nhận mật khẩu',
    loginBtn:           'ĐĂNG NHẬP',
    registerBtn:        'TẠO TÀI KHOẢN',
    loggingIn:          'Đang đăng nhập...',
    registering:        'Đang đăng ký...',
    noFullName:         'Vui lòng nhập họ và tên',
    noContact:          'Vui lòng nhập số điện thoại hoặc email',
    shortPassword:      'Mật khẩu tối thiểu 6 ký tự',
    passwordMismatch:   'Mật khẩu xác nhận không khớp',
    noIdentifier:       'Vui lòng nhập email hoặc số điện thoại',
    noPassword:         'Vui lòng nhập mật khẩu',
  },

  // Landing
  landing: {
    eyebrow:            'Đặt vé xe khách liên tỉnh',
    heroTitle:          'Đi đúng chuyến, ngồi đúng ghế, thanh toán an tâm.',
    heroSub:            'PAM Travel giúp bạn tìm chuyến, chọn ghế theo sơ đồ thực tế và nhận vé QR trong một luồng đặt vé gọn gàng.',
    origin:             'Điểm đi',
    destination:        'Điểm đến',
    date:               'Ngày đi',
    chooseOrigin:       'Chọn tỉnh đi',
    chooseDestination:  'Chọn tỉnh đến',
    search:             'Tìm chuyến',
    searching:          'Đang tìm...',
    routesEyebrow:      'Tuyến được đặt nhiều',
    routesTitle:        'Tuyến phổ biến',
    operatorsEyebrow:   'Đối tác vận chuyển',
    operatorsTitle:     'Nhà xe nổi bật',
    stepsEyebrow:       'Quy trình',
    stepsTitle:         'Đặt vé trong 4 bước',
    offersEyebrow:      'Khuyến mãi',
    offersTitle:        'Ưu đãi đang chạy',
    offerSub:           'Áp dụng khi đặt vé qua PAM Travel.',
    bookNow:            'Đặt ngay',
    missing:            'Vui lòng chọn đầy đủ điểm đi, điểm đến và ngày đi.',
    sameProvince:       'Điểm đi và điểm đến không được giống nhau.',
    searchFailed:       'Không tìm được chuyến phù hợp.',
    loginFirst:         'Đăng nhập để xem kết quả và chọn ghế.',
    steps: [
      { icon: '1', title: 'Tìm chuyến',    text: 'Chọn điểm đi, điểm đến và ngày khởi hành.' },
      { icon: '2', title: 'Chọn ghế',      text: 'Xem sơ đồ ghế và giữ chỗ trong thời gian thanh toán.' },
      { icon: '3', title: 'Thanh toán',    text: 'Xác nhận bằng PIN và OTP trong môi trường demo.' },
      { icon: '4', title: 'Nhận vé QR',    text: 'Lưu vé điện tử để tài xế soát khi lên xe.' },
    ],
    trustTrips:         'chuyến xe',
    trustOperators:     'nhà xe',
    trustRating:        'đánh giá',
    trustSupport:       'hỗ trợ',
  },

  // Home
  home: {
    title:        'TÌM CHUYẾN XE',
    subtitle:     'PHÙ HỢP VỚI BẠN',
    heroSub:      'Đặt vé nhanh chóng — chọn ghế theo ý muốn — thanh toán an toàn',
    originLabel:  'Điểm đi',
    destLabel:    'Điểm đến',
    dateLabel:    'Ngày đi',
    searchBtn:    'TÌM CHUYẾN →',
    searching:    'Đang tìm...',
    chooseOrigin: '-- Chọn tỉnh --',
    chooseDest:   '-- Chọn tỉnh --',
    errOrigin:    'Vui lòng chọn điểm đi',
    errDest:      'Vui lòng chọn điểm đến',
    errSame:      'Điểm đi và điểm đến không được giống nhau',
    errLoad:      'Không tải được danh sách tỉnh thành',
  },

  // Search
  search: {
    title:          'KẾT QUẢ TÌM KIẾM',
    searchAgain:    '← Tìm lại',
    loading:        'Đang tải chuyến xe...',
    noTrips:        'Không có chuyến xe',
    noTripsSub:     'Thử chọn ngày khác hoặc tuyến đường khác',
    searchAgainBtn: 'Tìm kiếm lại',
    filterTitle:    'Bộ lọc tìm kiếm',
    clearFilter:    'Xoá lọc',
    filterOperator: 'Nhà xe',
    filterVehicle:  'Loại xe',
    filterTime:     'Khung giờ đi',
    morning:        'Sáng (00:00 - 12:00)',
    afternoon:      'Chiều (12:00 - 18:00)',
    evening:        'Tối (18:00 - 24:00)',
    found:          'Tìm thấy',
    trips:          'chuyến xe',
    sortLabel:      'Sắp xếp:',
    sortPriceAsc:   'Giá tăng dần',
    sortPriceDesc:  'Giá giảm dần',
    sortTimeAsc:    'Giờ đi sớm nhất',
    sortTimeDesc:   'Giờ đi muộn nhất',
    noFiltered:     'Không có kết quả phù hợp',
    noFilteredSub:  'Hãy thử xoá bớt các bộ lọc đang chọn',
    resetFilters:   'Xoá toàn bộ lọc',
    seats:          'chỗ',
    selectBtn:      'Chọn ghế →',
  },

  // Seat map
  seatMap: {
    loading:      'Đang tải sơ đồ ghế...',
    available:    'Trống',
    locked:       'Đang giữ',
    confirmed:    'Đã đặt',
    selected:     'Đang chọn',
    floor:        'Tầng',
    selectedTitle:'GHẾ ĐÃ CHỌN',
    noSeat:       'Chưa chọn ghế nào',
    priceLabel:   'ghế ×',
    total:        'Tổng',
    bookBtn:      'ĐẶT',
    seatsSuffix:  'GHẾ →',
    booking:      'Đang đặt chỗ...',
    maxNote:      'Tối đa 5 ghế mỗi lần đặt',
    errMax:       'Tối đa 5 ghế mỗi lần đặt',
    errFail:      'Đặt chỗ thất bại',
    perSeat:      'đ/ghế',
  },

  // Booking
  booking: {
    loading:          'Đang tải thông tin...',
    countdownLabel:   '⏱ Ghế được giữ trong',
    countdownNote:    '— Hoàn tất trước khi hết giờ',
    passengerTitle:   'THÔNG TIN HÀNH KHÁCH',
    passenger:        'Hành khách',
    isSelf:           'Tôi là người đi',
    nameLabel:        'Họ và tên *',
    phoneLabel:       'Số điện thoại *',
    namePlaceholder:  'Nguyễn Văn A',
    phonePlaceholder: '0901234567',
    stopsTitle:       'ĐIỂM ĐÓN & TRẢ',
    loadingStops:     'Đang tải điểm dừng...',
    pickupLabel:      'Điểm đón *',
    dropoffLabel:     'Điểm trả *',
    pickupPlaceholder:'-- Chọn điểm đón --',
    dropoffPlaceholder:'-- Chọn điểm trả --',
    summaryTitle:     'TÓM TẮT ĐƠN',
    selectedSeats:    'Ghế đã chọn',
    total:            'Tổng tiền',
    continueBtn:      'TIẾP TỤC THANH TOÁN →',
    processing:       'Đang xử lý...',
    expired:          'Đã hết giờ giữ ghế',
    secure:           '🔒 Thông tin được bảo mật',
    errName:          'Vui lòng nhập họ tên',
    errPhone:         'Vui lòng nhập số điện thoại',
    errPhoneInvalid:  'Số điện thoại không hợp lệ',
    errPickup:        'Vui lòng chọn điểm đón',
    errDropoff:       'Vui lòng chọn điểm trả',
    errStops:         'Không tải được điểm dừng',
    cancelWarning:    '⚠️ Lưu ý: Sau khi thanh toán, hủy vé sẽ bị tính phí 10% (hoàn lại 90% giá trị vé).',
  },

  // Payment
  payment: {
    step1:          'Xác nhận PIN',
    step2:          'Nhập OTP',
    step3:          'Hoàn tất',
    methodTitle:    'PHƯƠNG THỨC THANH TOÁN',
    cancelWarning:  '⚠️ Hủy vé sau khi thanh toán sẽ mất 10% phí (hoàn 90%).',
    pinTitle:       'MẬT KHẨU THANH TOÁN',
    pinNote:        'Nhập PIN 6 số bạn đã cài đặt',
    setPinLabel:    'Chưa cài PIN?',
    setPinNewLabel: 'Nhập PIN mới (6 số)',
    setPinBtn:      'Cài PIN',
    setPinSetting:  '...',
    confirmBtn:     'XÁC NHẬN →',
    processing:     'Đang xử lý...',
    otpTitle:       'XÁC NHẬN OTP',
    otpNote:        'Mã OTP đã được gửi đến tài khoản của bạn.',
    otpDevLabel:    '(Dev mode: OTP = ',
    otpInput:       'Nhập mã 6 số',
    confirmPayBtn:  'XÁC NHẬN THANH TOÁN →',
    confirming:     'Đang xác nhận...',
    backBtn:        '← Quay lại',
    successTitle:   'THANH TOÁN THÀNH CÔNG',
    successSub:     'Vé điện tử đã được phát hành',
    ticketLabel:    'MÃ VÉ: #',
    viewTicketsBtn: 'XEM VÉ CỦA TÔI →',
    orderTitle:     'ĐƠN HÀNG',
    seats:          'Ghế',
    errPin:         'Vui lòng nhập PIN 6 số',
    errOtp:         'Vui lòng nhập OTP 6 số',
    errConfirmFail: 'Xác nhận thất bại',
    errOtpFail:     'Xác nhận OTP thất bại',
    walletGateway:  'Tài khoản cá nhân (Số dư: ',
    vnpay:          'VNPay',
    momo:           'MoMo',
    card:           'Thẻ tín dụng',
    cash:           'Tiền mặt (trả tài xế)',
    cashNote:       'Thanh toán trực tiếp cho tài xế khi lên xe. Vé QR sẽ được phát sau khi tài xế xác nhận.',
    cashBtn:        'XÁC NHẬN THANH TOÁN TIỀN MẶT →',
    cashSuccessTitle: 'ĐÃ GHI NHẬN TIỀN MẶT',
    cashSuccessSub:   'Vui lòng thanh toán cho tài xế khi lên xe. Vé QR sẽ hiện sau khi tài xế xác nhận.',
  },

  // My Tickets
  tickets: {
    title:        'VÉ CỦA TÔI',
    sub:          'Lịch sử đặt vé và vé điện tử',
    filterAll:    'Tất cả',
    filterConf:   'Đã xác nhận',
    filterPend:   'Chờ thanh toán',
    filterCanc:   'Đã hủy',
    loading:      'Đang tải vé...',
    emptyTitle:   'Chưa có vé nào',
    emptySub:     'Đặt vé ngay để bắt đầu hành trình',
    bookNow:      'ĐẶT VÉ NGAY',
    totalLabel:   'Tổng tiền',
    ticketLabel:  'VÉ ĐIỆN TỬ',
    tripInfo:     'THÔNG TIN CHUYẾN',
    bookingId:    'Mã đặt vé',
    seatsLabel:   'Ghế',
    bookedAt:     'Ngày đặt',
    totalAmount:  'Tổng tiền',
    payNow:       'Thanh toán ngay',
    cancelFree:   'Hủy đặt vé (Không mất phí)',
    refundNote:   '⚠️ Vé đã thanh toán. Hủy vé sẽ được hoàn lại',
    refundRate:   '90%',
    refundSuffix: 'vào tài khoản cá nhân.',
    loyalExempt:  'Khách hàng thân thiết được miễn phí hủy vé',
    cancelBtn:    'HỦY VÉ & NHẬN HOÀN TIỀN',
    cancelling:   'Đang xử lý hủy...',
    cancellingFree: 'Đang hủy...',
    confirmCancel:  'Bạn có chắc chắn muốn hủy đơn đặt vé này không?',
    cancelSuccess:  'Hủy vé thành công! Số tiền hoàn lại đã được cộng vào ví của bạn (nếu có).',
    statusConf:   'Đã xác nhận',
    statusPend:   'Chờ thanh toán',
    statusCash:   'Chờ xác nhận tiền mặt',
    statusCanc:   'Đã hủy',
    statusComp:   'Hoàn thành',
    filterCash:   'Tiền mặt',
    cashPendingNote: 'Đơn đang chờ tài xế xác nhận đã thu tiền. Vé QR sẽ hiện sau khi xác nhận.',
  },

  // Settings
  settings: {
    title:          'Cài đặt cá nhân',
    sub:            'Quản lý hồ sơ, ảnh đại diện và mã PIN thanh toán.',
    walletLabel:    'Số dư ví',
    profileTitle:   'Thông tin tài khoản',
    chooseAvatar:   'Chọn ảnh',
    fullName:       'Họ và tên',
    phone:          'Số điện thoại',
    email:          'Email',
    saveProfile:    'Lưu thông tin',
    saving:         'Đang lưu...',
    profileOk:      'Đã cập nhật thông tin tài khoản.',
    pinTitle:       'Mã PIN thanh toán',
    pinSub:         'PIN gồm 6 chữ số, dùng khi thanh toán vé hoặc nạp tiền vào ví.',
    newPin:         'PIN mới',
    confirmPin:     'Nhập lại PIN',
    savePin:        'Cập nhật PIN',
    savingPin:      'Đang cập nhật...',
    pinOk:          'Đã cập nhật PIN thanh toán.',
    tierTitle:      'Phân hạng thân thiết',
    tierSub:        'Phần giảm giá theo hạng sẽ được nối ở phase loyalty.',
    trips:          'chuyến',
    tickets:        'vé',
    rechargeTitle:  'Nạp tiền tài khoản cá nhân',
    rechargeSub:    'Nạp tiền giả lập vào tài khoản để thực hiện mua vé.',
    amountLabel:    'Số tiền nạp (đ)',
    amountPlaceholder: 'Nhập số tiền',
    pinLabel:       'Mã PIN thanh toán',
    rechargeBtn:    'Nạp tiền ngay',
    recharging:     'Đang nạp...',
    minAmount:      'Số tiền nạp tối thiểu là 10.000đ.',
    pinInvalid:     'PIN phải gồm đúng 6 chữ số.',
    pinMismatch:    'PIN nhập lại không khớp.',
    walletHistory:  'Lịch sử giao dịch',
    noTransactions: 'Chưa có giao dịch nào',
    otpTitle:       'Nhập OTP nạp tiền',
    otpConfirmBtn:  'Xác nhận nạp tiền',
    txTopup:        'Nạp tiền',
    txPayment:      'Thanh toán vé',
    txRefund:       'Hoàn tiền',
    txBonus:        'Thưởng',
  },

  // Admin
  admin: {
    tabs: {
      operators:'🏢 Nhà xe',
      trips:    '🚌 Chuyến xe',
      bookings: '🎫 Đặt vé',
      users:    '👤 Người dùng',
      payments: '💳 Thanh toán',
      stats:    '📊 Thống kê',
    },
    operators:     'NHÀ XE',
    operatorsTitle:'DANH SÁCH NHÀ XE',
    addOperator:   '+ Thêm nhà xe',
    editOperator:  'Sửa nhà xe',
    newOperator:   'Thêm nhà xe mới',
    saveOperator:  'Lưu',
    opName:        'Tên nhà xe *',
    opHotline:     'Hotline',
    opDesc:        'Mô tả',
    opInfo:        'Thông tin',
    opVehicles:    'Xe',
    opTrips:       'Chuyến đi',
    activate:      'Kích hoạt',
    deactivate:    'Vô hiệu hóa',
    confirmDeleteOp: 'Bạn có chắc muốn xóa nhà xe này?',
    trips:       'DANH SÁCH CHUYẾN XE',
    bookings:    'ĐƠN ĐẶT VÉ',
    users:       'NGƯỜI DÙNG',
    payments:    'THANH TOÁN',
    stats:       'THỐNG KÊ DOANH THU',
    statsSubtitle: '30 ngày gần nhất',
    loading:     'Đang tải...',
    noData:      'Không có dữ liệu',
    allStatus:   'Tất cả trạng thái',
    allRoles:    'Tất cả vai trò',
    allGateways: 'Tất cả cổng',
    revenue:     'Tổng doanh thu',
    success:     'Giao dịch thành công',
    confirmed:   'Đơn đặt xác nhận',
    cancelled:   'Đơn đã hủy',
    revenueChart:'Doanh thu theo ngày',
    noRevenue:   'Chưa có dữ liệu giao dịch trong 30 ngày',
    bookingStatus:'Trạng thái đơn đặt vé',
    totalOrders: 'đơn',
    topDays:     'Top ngày doanh thu cao nhất',
    avg:         'TB/GD',
    transactions:'Số giao dịch',
    tableId:     'ID',
    tableRoute:  'Tuyến',
    tableOp:     'Nhà xe',
    tableDep:    'Khởi hành',
    tablePrice:  'Giá',
    tableStatus: 'Trạng thái',
    tableActions:'Hành động',
    tableCustomer:'Khách hàng',
    tableTotal:  'Tổng tiền',
    tableBookedAt:'Ngày đặt',
    tableFullName:'Họ tên',
    tablePhone:  'Số điện thoại',
    tableEmail:  'Email / SĐT',
    tableRole:   'Vai trò',
    tableActive: 'Trạng thái',
    tableCreated:'Ngày tạo',
    tableBooking:'Booking',
    tableGateway:'Cổng TT',
    tableTxnId:  'Mã giao dịch',
    tablePaidAt: 'Thời gian',
    // Trip CRUD
    addTrip:       '+ Thêm chuyến',
    editTrip:      'Sửa chuyến',
    newTrip:       'Thêm chuyến mới',
    deleteTrip:    'Xóa chuyến',
    confirmDelete: 'Bạn có chắc muốn xóa chuyến #ID? Hành động này không thể hoàn tác.',
    saveTrip:      'Lưu chuyến',
    saving:        'Đang lưu...',
    cancel:        'Hủy',
    formRoute:     'Tuyến đường *',
    formVehicle:   'Phương tiện *',
    formOperator:  'Nhà xe *',
    formDeparture: 'Giờ khởi hành *',
    formArrival:   'Giờ đến *',
    formPrice:     'Giá ghi đè (đ)',
    formPricePlaceholder: 'Để trống = dùng giá tuyến',
    chooseRoute:   '-- Chọn tuyến --',
    chooseVehicle: '-- Chọn xe --',
    chooseOperator:'-- Chọn nhà xe --',
    statusOpen:    'Mở chuyến',
    statusClose:   'Đóng chuyến',
    toggleOpening: 'Đang mở...',
    toggleClosing: 'Đang đóng...',
    deleteSuccess: 'Đã xóa chuyến thành công',
    createSuccess: 'Đã tạo chuyến mới thành công',
    updateSuccess: 'Đã cập nhật chuyến thành công',
    errRequired:   'Vui lòng điền đầy đủ thông tin bắt buộc',
    errArrival:    'Giờ đến phải sau giờ khởi hành',
    loadingForm:   'Đang tải dữ liệu form...',
  },

  // Driver
  driver: {
    myTrips:       'Chuyến của tôi',
    scanner:       'Soát vé',
    myTripsTitle:  'CHUYẾN CỦA TÔI',
    refresh:       '⟳ Làm mới',
    refreshing:    '⟳ Đang tải...',
    loading:       'Đang tải danh sách chuyến...',
    noTrips:       'Chưa có chuyến nào',
    noTripsSub:    'Liên hệ admin để được phân công chuyến xe',
    passengers:    'hành khách',
    viewPassengers:'Xem hành khách →',
    scanTickets:   'Soát vé',
    scanTitle:     'SOÁT VÉ',
    scanSub:       'Quét mã QR hoặc nhập thủ công để check-in hành khách',
    clearTrip:     '✕ Bỏ chọn chuyến',
    cameraTitle:   'QUÉT MÃ QR',
    startCamera:   'Bật Camera',
    stopCamera:    'Tắt Camera',
    cameraNote:    'Nhấn để bật camera',
    orLabel:       'hoặc',
    manualTitle:   'NHẬP THỦ CÔNG',
    manualPlaceholder: 'Nhập mã QR (VD: PAM-1-1-001)',
    checkBtn:      'KIỂM TRA',
    checking:      '...',
    resultTitle:   'KẾT QUẢ',
    waiting:       'Chờ quét vé...',
    checkingMsg:   'Đang kiểm tra...',
    validTitle:    'VÉ HỢP LỆ',
    validSub:      'Check-in thành công',
    invalidTitle:  'VÉ KHÔNG HỢP LỆ',
    nextScan:      'Quét vé tiếp theo',
    retry:         'Thử lại',
    historyTitle:  'LỊCH SỬ CA NÀY',
    tickets:       'vé',
    manifestTitle: 'MANIFEST HÀNH KHÁCH',
    manifestTotal: 'Tổng:',
    manifestCI:    'Check-in:',
    tblNum:        '#',
    tblPassenger:  'Hành khách',
    tblSeat:       'Ghế',
    tblPickup:     'Điểm đón',
    tblDropoff:    'Điểm trả',
    tblQr:         'Mã QR',
    tblStatus:     'Trạng thái vé',
    ticketIssued:  'Đã phát',
    ticketUsed:    'Đã check-in',
    ticketCancelled:'Đã hủy',
    confirmCash:    'Xác nhận đã thu tiền',
    confirmingCash: 'Đang xác nhận...',
    cashConfirmed:  'Đã xác nhận tiền mặt, vé QR đã phát hành',
    infoPassenger: 'Hành khách',
    infoPhone:     'Số điện thoại',
    infoSeat:      'Ghế',
    infoRoute:     'Tuyến',
    infoDep:       'Khởi hành',
    infoQr:        'Mã QR',
  },

  // Footer
  footer: {
    description: 'Nền tảng đặt vé xe khách, chọn ghế và quản lý vé điện tử cho hành khách liên tỉnh.',
    company:     'Pam Travel',
    routes:      'Tuyến phổ biến',
    operators:   'Nhà xe nổi bật',
    steps:       'Quy trình đặt vé',
    support:     'Hỗ trợ',
    offers:      'Ưu đãi',
    office:      'Văn phòng',
    made:        'Đồ án đặt vé xe khách trực tuyến',
  },

  // Header
  header: {
    routes:    'Tuyến phổ biến',
    operators: 'Nhà xe',
    offers:    'Ưu đãi',
    support:   'Hỗ trợ',
    theme:     'Đổi giao diện',
    login:     'Đăng nhập',
    register:  'Đăng ký',
  },
}

// ─── English copy ─────────────────────────────────────────────────────────────
const en = {
  nav: {
    home:       'Home',
    myTickets:  'My Tickets',
    scan:       'Scan Tickets',
    admin:      'Admin',
    settings:   'Account Settings',
    logout:     'Logout',
    back:       '← Back',
  },

  auth: {
    login:              'Login',
    register:           'Register',
    loginTitle:         'WELCOME',
    loginSub:           'Login with your email or phone number',
    registerTitle:      'CREATE ACCOUNT',
    registerSub:        'Register a new passenger account',
    identifier:         'Email or Phone Number',
    password:           'Password',
    fullName:           'Full Name',
    phone:              'Phone Number',
    email:              'Email',
    confirmPassword:    'Confirm Password',
    loginBtn:           'LOGIN',
    registerBtn:        'CREATE ACCOUNT',
    loggingIn:          'Logging in...',
    registering:        'Creating account...',
    noFullName:         'Please enter your full name',
    noContact:          'Please enter a phone number or email',
    shortPassword:      'Password must be at least 6 characters',
    passwordMismatch:   'Passwords do not match',
    noIdentifier:       'Please enter your email or phone number',
    noPassword:         'Please enter your password',
  },

  landing: {
    eyebrow:            'Intercity bus ticketing',
    heroTitle:          'Find the right trip, choose your seat, pay with confidence.',
    heroSub:            'PAM Travel helps passengers search routes, select seats from a live map, and receive QR tickets in one focused booking flow.',
    origin:             'Origin',
    destination:        'Destination',
    date:               'Date',
    chooseOrigin:       'Choose origin',
    chooseDestination:  'Choose destination',
    search:             'Search trips',
    searching:          'Searching...',
    routesEyebrow:      'Most booked',
    routesTitle:        'Popular routes',
    operatorsEyebrow:   'Transport partners',
    operatorsTitle:     'Featured operators',
    stepsEyebrow:       'Flow',
    stepsTitle:         'Book in 4 steps',
    offersEyebrow:      'Promotions',
    offersTitle:        'Current offers',
    offerSub:           'Available for bookings through PAM Travel.',
    bookNow:            'Book now',
    missing:            'Please choose origin, destination, and date.',
    sameProvince:       'Origin and destination must be different.',
    searchFailed:       'No matching trips found.',
    loginFirst:         'Login to view results and choose seats.',
    steps: [
      { icon: '1', title: 'Search',      text: 'Pick origin, destination, and departure date.' },
      { icon: '2', title: 'Choose seats',text: 'Use the seat map and hold seats during checkout.' },
      { icon: '3', title: 'Pay',         text: 'Confirm with PIN and OTP in the demo flow.' },
      { icon: '4', title: 'Get QR ticket',text: 'Show the digital ticket when boarding.' },
    ],
    trustTrips:     'trips',
    trustOperators: 'operators',
    trustRating:    'rating',
    trustSupport:   'support',
  },

  home: {
    title:        'FIND A BUS',
    subtitle:     'THAT SUITS YOU',
    heroSub:      'Book quickly — choose your own seat — pay securely',
    originLabel:  'Origin',
    destLabel:    'Destination',
    dateLabel:    'Date',
    searchBtn:    'SEARCH →',
    searching:    'Searching...',
    chooseOrigin: '-- Choose origin --',
    chooseDest:   '-- Choose destination --',
    errOrigin:    'Please choose origin',
    errDest:      'Please choose destination',
    errSame:      'Origin and destination must be different',
    errLoad:      'Could not load province list',
  },

  search: {
    title:          'SEARCH RESULTS',
    searchAgain:    '← Search again',
    loading:        'Loading trips...',
    noTrips:        'No trips available',
    noTripsSub:     'Try a different date or route',
    searchAgainBtn: 'Search again',
    filterTitle:    'Filters',
    clearFilter:    'Clear filters',
    filterOperator: 'Operator',
    filterVehicle:  'Vehicle type',
    filterTime:     'Departure time',
    morning:        'Morning (00:00 - 12:00)',
    afternoon:      'Afternoon (12:00 - 18:00)',
    evening:        'Evening (18:00 - 24:00)',
    found:          'Found',
    trips:          'trips',
    sortLabel:      'Sort:',
    sortPriceAsc:   'Price: Low to High',
    sortPriceDesc:  'Price: High to Low',
    sortTimeAsc:    'Earliest departure',
    sortTimeDesc:   'Latest departure',
    noFiltered:     'No matching results',
    noFilteredSub:  'Try removing some filters',
    resetFilters:   'Clear all filters',
    seats:          'seats',
    selectBtn:      'Choose seats →',
  },

  seatMap: {
    loading:      'Loading seat map...',
    available:    'Available',
    locked:       'Held',
    confirmed:    'Booked',
    selected:     'Selected',
    floor:        'Floor',
    selectedTitle:'SELECTED SEATS',
    noSeat:       'No seats selected',
    priceLabel:   'seats ×',
    total:        'Total',
    bookBtn:      'BOOK',
    seatsSuffix:  'SEATS →',
    booking:      'Booking...',
    maxNote:      'Max 5 seats per booking',
    errMax:       'Maximum 5 seats per booking',
    errFail:      'Booking failed',
    perSeat:      '/seat',
  },

  booking: {
    loading:          'Loading...',
    countdownLabel:   '⏱ Seats held for',
    countdownNote:    '— Complete before time runs out',
    passengerTitle:   'PASSENGER DETAILS',
    passenger:        'Passenger',
    isSelf:           'I am the traveller',
    nameLabel:        'Full name *',
    phoneLabel:       'Phone number *',
    namePlaceholder:  'John Doe',
    phonePlaceholder: '0901234567',
    stopsTitle:       'PICKUP & DROP-OFF',
    loadingStops:     'Loading stops...',
    pickupLabel:      'Pickup point *',
    dropoffLabel:     'Drop-off point *',
    pickupPlaceholder:'-- Choose pickup --',
    dropoffPlaceholder:'-- Choose drop-off --',
    summaryTitle:     'ORDER SUMMARY',
    selectedSeats:    'Selected seats',
    total:            'Total',
    continueBtn:      'CONTINUE TO PAYMENT →',
    processing:       'Processing...',
    expired:          'Seat hold expired',
    secure:           '🔒 Your information is secure',
    errName:          'Please enter full name',
    errPhone:         'Please enter phone number',
    errPhoneInvalid:  'Invalid phone number',
    errPickup:        'Please choose a pickup point',
    errDropoff:       'Please choose a drop-off point',
    errStops:         'Could not load stops',
    cancelWarning:    '⚠️ Note: After payment, cancelling a ticket incurs a 10% fee (90% refund).',
  },

  payment: {
    step1:          'Confirm PIN',
    step2:          'Enter OTP',
    step3:          'Complete',
    methodTitle:    'PAYMENT METHOD',
    cancelWarning:  '⚠️ Cancelling after payment incurs a 10% fee (90% refund).',
    pinTitle:       'PAYMENT PASSWORD',
    pinNote:        'Enter your 6-digit PIN',
    setPinLabel:    'No PIN yet?',
    setPinNewLabel: 'New PIN (6 digits)',
    setPinBtn:      'Set PIN',
    setPinSetting:  '...',
    confirmBtn:     'CONFIRM →',
    processing:     'Processing...',
    otpTitle:       'CONFIRM OTP',
    otpNote:        'An OTP has been sent to your account.',
    otpDevLabel:    '(Dev mode: OTP = ',
    otpInput:       'Enter 6-digit code',
    confirmPayBtn:  'CONFIRM PAYMENT →',
    confirming:     'Confirming...',
    backBtn:        '← Back',
    successTitle:   'PAYMENT SUCCESSFUL',
    successSub:     'Your e-tickets have been issued',
    ticketLabel:    'TICKET #',
    viewTicketsBtn: 'VIEW MY TICKETS →',
    orderTitle:     'ORDER',
    seats:          'Seats',
    errPin:         'Please enter a 6-digit PIN',
    errOtp:         'Please enter a 6-digit OTP',
    errConfirmFail: 'Confirmation failed',
    errOtpFail:     'OTP confirmation failed',
    walletGateway:  'Personal Wallet (Balance: ',
    vnpay:          'VNPay',
    momo:           'MoMo',
    card:           'Credit Card',
    cash:           'Cash (pay driver)',
    cashNote:       'Pay the driver when boarding. QR tickets are issued after driver confirmation.',
    cashBtn:        'CONFIRM CASH PAYMENT →',
    cashSuccessTitle: 'CASH PAYMENT RECORDED',
    cashSuccessSub:   'Pay the driver when boarding. QR tickets appear after driver confirmation.',
  },

  tickets: {
    title:        'MY TICKETS',
    sub:          'Booking history and e-tickets',
    filterAll:    'All',
    filterConf:   'Confirmed',
    filterPend:   'Pending payment',
    filterCanc:   'Cancelled',
    loading:      'Loading tickets...',
    emptyTitle:   'No tickets yet',
    emptySub:     'Book a trip to get started',
    bookNow:      'BOOK NOW',
    totalLabel:   'Total',
    ticketLabel:  'E-TICKETS',
    tripInfo:     'TRIP DETAILS',
    bookingId:    'Booking ID',
    seatsLabel:   'Seats',
    bookedAt:     'Booked at',
    totalAmount:  'Total amount',
    payNow:       'Pay now',
    cancelFree:   'Cancel booking (No fee)',
    refundNote:   '⚠️ This booking was paid. Cancelling will refund',
    refundRate:   '90%',
    refundSuffix: 'to your wallet.',
    loyalExempt:  'Loyal customers are exempt from cancellation fees',
    cancelBtn:    'CANCEL & GET REFUND',
    cancelling:   'Cancelling...',
    cancellingFree: 'Cancelling...',
    confirmCancel:  'Are you sure you want to cancel this booking?',
    cancelSuccess:  'Booking cancelled! Refund has been added to your wallet (if applicable).',
    statusConf:   'Confirmed',
    statusPend:   'Pending payment',
    statusCash:   'Awaiting cash confirm',
    statusCanc:   'Cancelled',
    statusComp:   'Completed',
    filterCash:   'Cash pending',
    cashPendingNote: 'Waiting for driver to confirm cash payment. QR tickets will appear after confirmation.',
  },

  settings: {
    title:          'Account Settings',
    sub:            'Manage your profile, avatar and payment PIN.',
    walletLabel:    'Wallet balance',
    profileTitle:   'Account information',
    chooseAvatar:   'Choose photo',
    fullName:       'Full name',
    phone:          'Phone number',
    email:          'Email',
    saveProfile:    'Save changes',
    saving:         'Saving...',
    profileOk:      'Profile updated successfully.',
    pinTitle:       'Payment PIN',
    pinSub:         'A 6-digit PIN used when paying for tickets or topping up your wallet.',
    newPin:         'New PIN',
    confirmPin:     'Confirm PIN',
    savePin:        'Update PIN',
    savingPin:      'Updating...',
    pinOk:          'PIN updated successfully.',
    tierTitle:      'Loyalty tier',
    tierSub:        'Discount benefits per tier will be added in the loyalty phase.',
    trips:          'trips',
    tickets:        'tickets',
    rechargeTitle:  'Top up wallet',
    rechargeSub:    'Simulate a top-up to use for ticket purchases.',
    amountLabel:    'Amount (VND)',
    amountPlaceholder: 'Enter amount',
    pinLabel:       'Payment PIN',
    rechargeBtn:    'Top up now',
    recharging:     'Processing...',
    minAmount:      'Minimum top-up is 10,000 VND.',
    pinInvalid:     'PIN must be exactly 6 digits.',
    pinMismatch:    'PINs do not match.',
    walletHistory:  'Transaction history',
    noTransactions: 'No transactions yet',
    otpTitle:       'Enter top-up OTP',
    otpConfirmBtn:  'Confirm top-up',
    txTopup:        'Top-up',
    txPayment:      'Ticket payment',
    txRefund:       'Refund',
    txBonus:        'Bonus',
  },

  admin: {
    tabs: {
      operators:'🏢 Operators',
      trips:    '🚌 Trips',
      bookings: '🎫 Bookings',
      users:    '👤 Users',
      payments: '💳 Payments',
      stats:    '📊 Stats',
    },
    operators:     'OPERATORS',
    operatorsTitle:'OPERATOR LIST',
    addOperator:   '+ Add Operator',
    editOperator:  'Edit Operator',
    newOperator:   'New Operator',
    saveOperator:  'Save',
    opName:        'Operator name *',
    opHotline:     'Hotline',
    opDesc:        'Description',
    opInfo:        'Info',
    opVehicles:    'Vehicles',
    opTrips:       'Trips',
    activate:      'Activate',
    deactivate:    'Deactivate',
    confirmDeleteOp: 'Are you sure you want to delete this operator?',
    trips:       'TRIP LIST',
    bookings:    'BOOKINGS',
    users:       'USERS',
    payments:    'PAYMENTS',
    stats:       'REVENUE STATS',
    statsSubtitle: 'Last 30 days',
    loading:     'Loading...',
    noData:      'No data available',
    allStatus:   'All statuses',
    allRoles:    'All roles',
    allGateways: 'All gateways',
    revenue:     'Total revenue',
    success:     'Successful transactions',
    confirmed:   'Confirmed bookings',
    cancelled:   'Cancelled bookings',
    revenueChart:'Revenue by day',
    noRevenue:   'No transaction data in the last 30 days',
    bookingStatus:'Booking status',
    totalOrders: 'orders',
    topDays:     'Top revenue days',
    avg:         'Avg/txn',
    transactions:'Transactions',
    tableId:     'ID',
    tableRoute:  'Route',
    tableOp:     'Operator',
    tableDep:    'Departure',
    tablePrice:  'Price',
    tableStatus: 'Status',
    tableActions:'Actions',
    tableCustomer:'Customer',
    tableTotal:  'Total',
    tableBookedAt:'Booked at',
    tableFullName:'Full name',
    tablePhone:  'Phone',
    tableEmail:  'Email / Phone',
    tableRole:   'Role',
    tableActive: 'Status',
    tableCreated:'Created',
    tableBooking:'Booking',
    tableGateway:'Gateway',
    tableTxnId:  'Transaction ID',
    tablePaidAt: 'Paid at',
    // Trip CRUD
    addTrip:       '+ Add Trip',
    editTrip:      'Edit Trip',
    newTrip:       'New Trip',
    deleteTrip:    'Delete Trip',
    confirmDelete: 'Are you sure you want to delete trip #ID? This cannot be undone.',
    saveTrip:      'Save Trip',
    saving:        'Saving...',
    cancel:        'Cancel',
    formRoute:     'Route *',
    formVehicle:   'Vehicle *',
    formOperator:  'Operator *',
    formDeparture: 'Departure time *',
    formArrival:   'Arrival time *',
    formPrice:     'Price override (VND)',
    formPricePlaceholder: 'Leave empty = use route price',
    chooseRoute:   '-- Choose route --',
    chooseVehicle: '-- Choose vehicle --',
    chooseOperator:'-- Choose operator --',
    statusOpen:    'Open trip',
    statusClose:   'Close trip',
    toggleOpening: 'Opening...',
    toggleClosing: 'Closing...',
    deleteSuccess: 'Trip deleted successfully',
    createSuccess: 'Trip created successfully',
    updateSuccess: 'Trip updated successfully',
    errRequired:   'Please fill in all required fields',
    errArrival:    'Arrival time must be after departure time',
    loadingForm:   'Loading form data...',
  },

  driver: {
    myTrips:       'My Trips',
    scanner:       'Scan Tickets',
    myTripsTitle:  'MY TRIPS',
    refresh:       '⟳ Refresh',
    refreshing:    '⟳ Loading...',
    loading:       'Loading trips...',
    noTrips:       'No trips assigned',
    noTripsSub:    'Contact admin to be assigned a trip',
    passengers:    'passengers',
    viewPassengers:'View passengers →',
    scanTickets:   'Scan',
    scanTitle:     'TICKET SCANNER',
    scanSub:       'Scan QR code or enter manually to check in passengers',
    clearTrip:     '✕ Clear trip',
    cameraTitle:   'SCAN QR CODE',
    startCamera:   'Start Camera',
    stopCamera:    'Stop Camera',
    cameraNote:    'Tap to enable camera',
    orLabel:       'or',
    manualTitle:   'MANUAL ENTRY',
    manualPlaceholder: 'Enter QR code (e.g. PAM-1-1-001)',
    checkBtn:      'CHECK',
    checking:      '...',
    resultTitle:   'RESULT',
    waiting:       'Waiting for scan...',
    checkingMsg:   'Checking...',
    validTitle:    'VALID TICKET',
    validSub:      'Check-in successful',
    invalidTitle:  'INVALID TICKET',
    nextScan:      'Scan next ticket',
    retry:         'Try again',
    historyTitle:  'THIS SESSION',
    tickets:       'tickets',
    manifestTitle: 'PASSENGER MANIFEST',
    manifestTotal: 'Total:',
    manifestCI:    'Checked in:',
    tblNum:        '#',
    tblPassenger:  'Passenger',
    tblSeat:       'Seat',
    tblPickup:     'Pickup',
    tblDropoff:    'Drop-off',
    tblQr:         'QR Code',
    tblStatus:     'Ticket status',
    ticketIssued:  'Issued',
    ticketUsed:    'Checked in',
    ticketCancelled:'Cancelled',
    confirmCash:    'Confirm cash received',
    confirmingCash: 'Confirming...',
    cashConfirmed:  'Cash confirmed, QR tickets issued',
    infoPassenger: 'Passenger',
    infoPhone:     'Phone',
    infoSeat:      'Seat',
    infoRoute:     'Route',
    infoDep:       'Departure',
    infoQr:        'QR Code',
  },

  footer: {
    description: 'Intercity bus booking platform with seat selection and digital ticket management.',
    company:     'Pam Travel',
    routes:      'Popular routes',
    operators:   'Featured operators',
    steps:       'Booking flow',
    support:     'Support',
    offers:      'Offers',
    office:      'Office',
    made:        'Online bus ticketing final project',
  },

  header: {
    routes:    'Popular Routes',
    operators: 'Operators',
    offers:    'Offers',
    support:   'Support',
    theme:     'Toggle theme',
    login:     'Login',
    register:  'Register',
  },
}

// ─── Store ────────────────────────────────────────────────────────────────────
export const useUiStore = defineStore('ui', {
  state: () => ({
    darkMode: localStorage.getItem('pam_dark') === 'true',
    locale:   localStorage.getItem('pam_locale') || 'vi',
  }),

  getters: {
    t: (state) => (state.locale === 'en' ? en : vi),
    isDark: (state) => state.darkMode,
    isEn:   (state) => state.locale === 'en',
  },

  actions: {
    toggleDark() {
      this.darkMode = !this.darkMode
      localStorage.setItem('pam_dark', String(this.darkMode))
      this._applyDark()
    },

    toggleLocale() {
      this.locale = this.locale === 'vi' ? 'en' : 'vi'
      localStorage.setItem('pam_locale', this.locale)
    },

    setLocale(loc) {
      this.locale = loc
      localStorage.setItem('pam_locale', loc)
    },

    // Call once on app mount to sync class with persisted state
    _applyDark() {
      if (this.darkMode) {
        document.documentElement.classList.add('dark')
      } else {
        document.documentElement.classList.remove('dark')
      }
    },

    init() {
      this._applyDark()
    },
  },
})